# -*- coding: utf-8 -*-
"""plot-a-partir-de-txt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1evVCKv7YIWda02t0e3mmEVXDfndVpEZK

Obtenção dos dados (salvar os arquivos no projeto do colab, caso contrário alterar linha 17) 
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

archive_name = '' ##Insira o nome do arquivo a ser lido da pasta /archives
dataFrame = pd.read_csv(f'/content/{archive_name}.txt', delim_whitespace=True)

column_x_label = '' #Insira o nome da coluna a ser lida para o eixo x
column_y_label = '' #Insira o nome da coluna a ser lida para o eixo y

column_x = dataFrame[column_x_label].values
column_y = dataFrame[column_y_label].values

"""Imprimindo o gráfico"""

plt.style.use('seaborn-v0_8-darkgrid')
fig, ax = plt.subplots()

label_x = '' ## Insira o rótulo do eixo x
label_y = '' ## Insira o rótulo do eixo y
title = f'{label_x} x {label_y}'
graph_color = 'red' ## Insira a cor do gráfico

ax.plot(column_x, column_y, color = graph_color)
ax.set_title(title)
ax.set_xlabel(label_x)
ax.set_ylabel(label_y)

max_x, min_x, max_y, min_y =  max(column_x), min(column_x), max(column_y), min(column_y) ## Insira os valores máximos e mínimos a serem plotados nos eixos x e y

ax.set(xlim = (min_x*0.90, max_x*1.10), xticks=np.linspace(min_x, max_x, 11), ylim = (min_y*0.90, max_y*1.10), yticks=np.linspace(min_y, max_y, 11))

plt.show()
